##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/libmatemixer
    - gcc
    - git
    - glib2
    - intltool
    - libpulse
    - make
    - mate-common
    - which

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/libmatemixer
    - git
    - libasound2-dev
    - libglib2.0-dev
    - libpulse-dev
    - make
    - mate-common

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/libmatemixer.git
    - alsa-lib-devel
    - gcc
    - git
    - make
    - mate-common
    - pulseaudio-libs-devel
    - redhat-rpm-config

  ubuntu:
    - git
    - libasound2-dev
    - libglib2.0-dev
    - libpulse-dev
    - make
    - mate-common

variables:
  - CFLAGS="-Wall -Werror=format-security"

before_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     curl -Ls -o debian.sh https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/debian.sh
  -     bash ./debian.sh
  - fi

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: libmatemixer-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release

